spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/spring-boot-mybatis
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
      cluster:
        nodes:
          - redis1.itclj.com:7000
          - redis1.itclj.com:7001
          - redis2.itclj.com:7002
          - redis2.itclj.com:7003
          - redis3.itclj.com:7004
          - redis3.itclj.com:7005
        max-redirects: 5
      timeout: 3000
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1



mybatis:
    mapperLocations: classpath:mapper/**/*.xml